### ISSUE TITLE
Readme section unclear

### ISSUE THREAD

**Issue by anakimluke** [tenacityteam/tenacity-legacy#238]
Heading in question:

    ## Why did this project fork audacity/audacity?

It was confusing to me reading this sentence; it took me a while to realize the extra `/audacity` is not a typo, but a reference to the repository name and owner.

Maybe this could be worded differently? Maybe as 'why did this project fork the original audacity?' or something like that.

**Comment by caughtquick** [comment]
I'll make a PR fixing this tomorrow if someone doesn't get to it before me.

**Comment by n0toose** [comment]
> I'll make a PR fixing this tomorrow if someone doesn't get to it before me.

While you're at it, there's also a couple of other things that need to be fixed in the README, such as updating the description of Tenacity to `Tenacity is an easy-to-use, privacy-friendly, FLOSS, cross-platform multi-track audio editor/recorder for Windows, macOS, Linux and other operating systems. It is based on the widely popular [Audacity](https://www.audacityteam.org/) and is being developed by a wide, diverse group of volunteers.`.

**Comment by caughtquick** [comment]
Sure, I'll get to it within the next 12 hours.
