### ISSUE TITLE
Change selection Icon

### ISSUE THREAD

**Issue by NotAProton** [tenacityteam/tenacity-legacy#287]
![image](https://user-images.githubusercontent.com/81463636/126032718-6bdebc76-7665-4da5-9bd2-67d4af33ba88.png)

This looks outdated and scales horribly on high resolution displays.

---
Info
OS: Windows 10
Display: 1920×1080p

**Comment by n0toose** [comment]
Hi, I'd like to know the following:
- OS
- Monitor resolution

**Comment by NotAProton** [comment]
@panos Updated the issue

**Comment by n0toose** [comment]
This seems relevant to `wxCURSOR_ARROW`. Seems to look good on Linux, yet astoundingly horrendous on Windows.

We could:
- Design our own icon in .xpm format and apply it anywhere
- Only apply our custom arrows on Windows.
- Relevant code snippet in `wxWidgets`: https://github.com/wxWidgets/wxWidgets/blob/46867f591c24152d5546cefd31b317f6593e24db/src/msw/cursor.cpp#L326
- [Windows documentation](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-loadcursora)

Not sure what is up in GTK:
https://github.com/wxWidgets/wxWidgets/blob/0943beb24160c90b6dc74532e7c77230e634abb5/src/gtk/cursor.cpp#L233

**Comment by akleja** [comment]
Since there already are quite a number of custom mouse pointers that's applied on all platforms (I think, at least on windows and linux) it would make sense to use custom ones in this context as well. When we're at it we might as well update the old ones as well. They all look quite outdated.
That would mean:
* Draw some new mouse pointers and replace the old
* Draw the new arrows
* Apply custom arrows for all platforms.

Since the xpm format only has 1bit transparency there needs to be some care taken on a pixel basis.
Also keeping the hotspots at 16x16 pixels might be a good idea to minimize unnecessary changes. Except for the Draw cursor that has an offset hotspot.

Adding new cursors seems to be done by:
* adding them to images/Cursors32 and images/Cursors.h
* calling MakeCursor where they should be used

I'll start drawing right away and see how things come along.

**Comment by akleja** [comment]
Here's the initial result of my reworked mouse cursors:

My proposed mouse cursors:
![mousecursors_new](https://user-images.githubusercontent.com/49785979/126825732-bd8278cb-a72d-4d77-b4d0-59d0c2575734.png)

Some alternatives (that are less of a change):
![mousecursors_alt](https://user-images.githubusercontent.com/49785979/126825729-02f07622-cf30-4fcf-af4f-fbe41008e9a3.png)

Current mouse cursors:
![mousecursors_old](https://user-images.githubusercontent.com/49785979/126824785-c3861ebd-b05d-4df2-a32a-3defef6e18be.png)

I went with white fill and black lines because it's something of a standard, and it also is way more visible on the high contrast theme than any alternatives
I haven't touched the stretch cursors since I haven't figured out when they're actually used.

**Comment by nbsp** [comment]
I prefer the `+`/`-` being inside the magnifying glass, and the bigger arrows in `|←` , but other than that everything in the first image looks great!

**Comment by fossdd** [comment]
I like the alternatives, they're more handy for users already using Audacity. This would imo a  big change for these people.

**Comment by akleja** [comment]
@SFR-git The problem with the +/- inside the magnifying glass is that for the plus one they block any background poking through. Might not be important though. I could go with either.

@fossdd I'm a bit split tbh. While I do see your point, I find the hand cursor both ugly and a bit strange. It also looks out of place on most systems no matter the style of hand you go for. The arrow ones i find way more intuitive.

Thoughts about the selection extension cursors? They're the most pressing atm

**Comment by akleja** [comment]
Also the hand cursor hasn't really been used in any bigger capacity (if at all?) until the recent additions of the Track Affordances
