### ISSUE TITLE
Update track menus

### ISSUE THREAD

**Issue by Reaper10** [tenacityteam/tenacity-legacy#316]
The is to update track menus by adding icon to it.

<img width="162" alt="menu" src="https://user-images.githubusercontent.com/8137561/126210129-eb76b49c-899b-44a9-a455-174f2149e0e0.PNG">

view options icons

multi view
![multi view](https://user-images.githubusercontent.com/8137561/126210432-390569af-f4f3-4745-a332-b07eb69e772c.png)

spectrum
![spectrum](https://user-images.githubusercontent.com/8137561/126210850-46a62e81-1918-441b-9283-e246dc7e4c9d.png)- [ ] I have read the specified guidelines for issues

waveform
![waveform](https://user-images.githubusercontent.com/8137561/126211548-a4178bf7-dbff-4807-b5af-d7a7652e75da.png)

[view icons.zip](https://github.com/tenacityteam/tenacity/files/6843244/view.icons.zip)

I will be adding more for the rest of the options soon

<img width="162" alt="menu" src="https://user-images.githubusercontent.com/8137561/126213075-f93c0dee-3a0c-455f-9041-6ef2c66b40d2.PNG">

wave color

**Comment by Semisol** [comment]
This issue is **invalid**.
1. Please collapse large images using a `<details>` tag.
2. Please be more descriptive about what you want added.
3. Please use [the feature request template](https://github.com/tenacityteam/tenacity/issues/new?assignees=&labels=&template=feature_request.md), blank template issues will be rejected (with exceptions).
4. I do not think you can add icons to the drop-down.

**Comment by awslabspl** [comment]
> This issue is **invalid**.
> 
> 1. Please collapse large images using a `<details>` tag.
> 2. Please be more descriptive about what you want added.
> 3. Please use [the feature request template](https://github.com/tenacityteam/tenacity/issues/new?assignees=&labels=&template=feature_request.md), blank template issues will be rejected (with exceptions).
> 4. I do not think you can add icons to the drop-down.

This is what makes me not to commit any code to this project: @Semisol instead of pointing things out, maybe you'll apply your corrections yourself?

Total lazyness.

**Comment by nbsp** [comment]
> This is what makes me not to commit any code to this project: @Semisol instead of pointing things out, maybe you'll apply your corrections yourself?

The reason we ask people to follow the instructions is so that we don't have to waste valuable time asking for more info, and instead spend it on fixing the problem. If you can't bother to follow a couple of steps, why should we bother looking at your issue?

Closing this issue as it is invalid -- please file another ticket when you try again.

**Comment by awslabspl** [comment]
> If you can't bother to follow a couple of steps, why should we bother looking at your issue?

Simply because you are staff of this project!

**Comment by fitojb** [comment]
@awslabspl Almost any FOSS project will ask you to file actionable tickets, which in other words are issues that focus on only one aspect. It’s a reasonable thing to ask from any bug filer.

We at Ubuntu have long given this link to people: https://www.chiark.greenend.org.uk/~sgtatham/bugs.html

Feel free to study it.

And no, you can’t expect “staff” (or in this case, volunteer contributors) to try to make sense of a bug report that is all over the place.
