### ISSUE TITLE
Put moderation in place and halt posts to vote-name issue

### ISSUE THREAD

**Issue by Sciss** [tenacityteam/tenacity-legacy#34]
Unfortunately, I think we (cookieengineer for now) should write protect the issues that are just spammed now. Put a proper communication channel in place (see other issues), and continue discussion when the trolls have moved on. And please ban abusive users. Thank you

**Comment by cookiengineer** [comment]
Yep, see #33 

(also keeping the other issue open doesn't make a difference as long as the trolls are busy)

**Comment by Sciss** [comment]
I think GitHub lets you easily rename an organization. So in order to share moderation, if you feel overwhelmed, you could fork the project to a new organization with a tentative name, add additional members/moderators, and the organization's name could be changed to the decided name at a later point.

Is it possible to ban users entirely from a project? Now would be a moment to do that with the five most spammy accounts.

**Comment by ecoflute** [comment]
#IStandWithSneed

**Comment by Trigex** [comment]
i can't sneed
![a68](https://user-images.githubusercontent.com/16647252/124522796-50382380-dda9-11eb-873c-6ca2fd96ecfc.jpg)

**Comment by Sciss** [comment]
@cookiengineer thanks for the add. I can close issues now, but seems I cannot delete comments. Is this a limitation of GH? Are you able to delete content?

**Comment by hitshoot-dev** [comment]
![gigachad_sneed](https://user-images.githubusercontent.com/85889844/124523790-859f3a00-ddc6-11eb-9dce-0a3800323730.png)
#IStandWithSneed

**Comment by koyafish** [comment]
I think you should stop installing telemetry in opensource software, you're ruining an iconic product

**Comment by cookiengineer** [comment]
> Is it possible to ban users entirely from a project? Now would be a moment to do that with the five most spammy accounts.

Yes, orga can be renamed easily when name is not taken yet. In the settings / danger zone.

Yes, orga lets you ban users, that's why I created it. In private repos I can block them "as myself / aka @cookiengineer" - but that's useless to the repository because they cannot be prevented from creating issues or commenting there. I was writing with @panos at the time when the raid started, and I kinda created this orga in a rush to get ahead of things :smile: :disappointed_relieved: 

There's also a setting that prevents new users from posting, which also helped a lot (but it's a temporary setting limited to max 7 days). But it didn't help against all the fake accounts that were created a month or two ago (even when they obviously were spamming accounts without any real source code or anything).
