### ISSUE TITLE
Add to windows package managers

### ISSUE THREAD

**Issue by sn1per1** [tenacityteam/tenacity-legacy#53]
Chocolatey is a package manager for windows like apt or pacman on Linux.
Chocolatey package after renaming and windows build is done? 
https://community.chocolatey.org/packages/

**Comment by zukigay** [comment]
can you also add a scoop package if possible?

**Comment by Tony-Klink** [comment]
And also winget?

**Comment by peepo5** [comment]
Good for windows package manager use :)

**Comment by ghost** [comment]
I guess also add to Windows 11 Microsoft Store once they accept Win32 apps (which they will, just wait a bit)

**Comment by marcthe12** [comment]
Chocolatey is nice, but I think winget and windows store is a better option as they are offical channels from MS.(Appstor doesn't audacity giving us some advantage

**Comment by fossdd** [comment]
> Chocolatey is a package manager for windows like apt or pacman on Linux.
> Chocolatey package after renaming and windows build is done?
> https://community.chocolatey.org/packages/

Does someone is able to package and maintain it for Chocolatey? Audacity is also packaged: https://community.chocolatey.org/packages/audacity. 

> can you also add a scoop package if possible?

If someone is ready to maintain it, it would be able. Looks like here are the config files (https://github.com/ScoopInstaller/Main/tree/master/bucket), so simple json files. They also can auto-update via github releases. So, for that we depend on https://github.com/tenacityteam/tenacity/issues/166

> And also winget?

If someone is willing to maintain it. It can also use github releases as download urls. Audacity is already packaged: https://github.com/microsoft/winget-pkgs/tree/master/manifests/a/Audacity/Audacity. Packaging guide: https://github.com/microsoft/winget-pkgs#submitting-a-package

> I guess also add to Windows 11 Microsoft Store once they accept Win32 apps (which they will, just wait a bit)

I guess that costs and requires and Microsoft account. It is very properitary.

**Comment by Reaper10** [comment]
There is [winget](https://github.com/microsoft/winget-cli)

**Comment by n0toose** [comment]
Fixed: https://community.chocolatey.org/packages/tenacity/

**Comment by peepo5** [comment]
It says - "virus scan did not pass".
That is an incredibly strange feature, especially happening to an open-sourced app.
Is there a way to remove this warning by providing the source code?

**Comment by n0toose** [comment]
You'd have to reach out to @A-d-r-i for this.

**Comment by A-d-r-i** [comment]
Hello everyone,
Indeed I am the maintainer of Tenacity on chocolatey. I sent the very first version ([0.1.0-alpha](https://community.chocolatey.org/packages/tenacity/0.1.0-alpha)) this morning.
This package is currently passing chocolatey's tests (basically the program is testing the installation of the package and checking for viruses).

> It says - "virus scan did not pass".

Virus test passed successfully and I don't see the error you are getting, but installing from this command works fine on my end (`--pre` is very important): `choco install tenacity --version=0.1.0-alpha --pre `

<p align="center"><img src="https://user-images.githubusercontent.com/27277698/135052087-efc390d4-e216-4a17-b314-e3a5cba709d6.png" width="500"/></p>

> Is there a way to remove this warning by providing the source code?

The "source code" for uploading the package (which is simply packaging the .exe file) is available here (*but I don't think there is any connection with the error you cite.*):

- [Global project](https://github.com/A-d-r-i/update_choco_package)
- [General file for Tenacity](https://github.com/A-d-r-i/update_choco_package/blob/main/send_tenacity.ps1)
- [Packaging folder](https://github.com/A-d-r-i/update_choco_package/tree/main/tenacity)

Currently, as there is no official stable release on github for Tenacity, I cannot automate the process. But as soon as the releases are published the update of the package will be done automatically.

---
❗ An installation error on the test machine is present on 0.1.0-alpha version. No worries I am in contact with the admins to resolve this. Since the package works perfectly locally and on the test environment provided by chocolatey, there is no reason why it should not become "all green"

Edit: Everything is fine, it is about an oversight of dependencies (see this [commit](https://github.com/A-d-r-i/update_choco_package/commit/871bd24776dac65e0d07a149c73bed0d45e4cdc3) - corrected in [0.1.0.001-alpha](https://community.chocolatey.org/packages/tenacity/0.1.0.001-alpha) version)

**Comment by peepo5** [comment]
It looks like chocolately updated the virustotal scan so it should be all good now. Nice work by the way.
