### ISSUE TITLE
Show wxWidgets version being used within Tenacity

### ISSUE THREAD

**Issue by n0toose** [tenacityteam/tenacity-legacy#612]
### Guidelines

- [X] I have read the guidelines.

### Is your feature request related to a problem? Please describe.

After our first release ships, we'll get a *lot* of attention. We recently brought back support for #300, which means that our program's quality may take a hit for the time being, but at least it'll work.

However, when users give us feedback or report bugs, we need to be fully aware of the scope of the situation, and that includes knowing the wxWidgets version being used, as this alters the behavior of Tenacity itself.

### Describe the solution you'd like

We need to detect the wxWidgets version being used, and show it somewhere convenient, so that a user can conveniently clarify which version of wxWidgets they're using to us. The About window may be the right place for this.

### Describe alternatives you've considered

It'd also be a good idea to add that to stderr/stdout and to the logs.

### This issue is not a duplicate

- [X] I have confirmed this issue isn't a duplicate.

**Comment by leio** [comment]
Note that wxWidgets injects its own shortcut for showing this information, which is a bit controversial, if you ask me. You can hit mouse middle button on top of many places while holding down Ctrl+Alt, e.g. the toolbar area or the about dialog (but not some custom control). You can see this in #300 in my screenshot, which is how I triggered that to be shown.

I think we should add this same information into our About Tenacity dialog "Build Information" tab directly, instead of having the user do magic keyboard+mouse incantations.

I could do this at some point if no-one beats me to it (but please do beat me on it :D)

**Comment by n0toose** [comment]
> I think we should add this same information into our About Tenacity dialog "Build Information" tab directly, instead of having the user do magic keyboard+mouse incantations.

That's what I sort of meant. Yep.
