### ISSUE TITLE
Create a chat room for real time communication

### ISSUE THREAD

**Issue by caughtquick** [tenacityteam/tenacity-legacy#7]
Maybe on Matrix or on IRC

**Comment by EricBright** [comment]
How about a group on Telegram? I just created one called Audacity Fork at https://t.me/AudioBakery. See if that might be of any help.

**Comment by DavidBuchanan314** [comment]
May I suggest #audacity-fork on libera.chat

**Comment by caughtquick** [comment]
> How about a group on Telegram? I just created one called Audacity Fork at https://t.me/AudioBakery. See if that might be of any help.

Telegram isn't a great choice for a FOSS project considering the server isn't open source

**Comment by caughtquick** [comment]
Matrix is a much better alternative to Telegram IMO, and IRC wouldn't be a bad idea either

**Comment by EricBright** [comment]
LibreOffice also uses Telegram, so, I thought if it is good enough for them, then it might be good enough for us. I don't know. Just a suggestion.

**Comment by caughtquick** [comment]
Yeah its not a bad choice

**Comment by hiimcody1** [comment]
There is a sizeable gathering happening on a Discord, but I'd prefer see something on a more open platform: https://discord.gg/D8JSWW4m

**Comment by caughtquick** [comment]
Yep, though the discord will probably be bridged to matrix and irc

**Comment by ajayyy** [comment]
https://matrix.to/#/#audiofork:libera.chat

#audiofork on liberachat

**Comment by Skynse** [comment]
I feel like Discord would be the best option.

**Comment by cookiengineer** [comment]
I'd also go for either Telegram or Matrix/Element to be honest, as most chats seem to have moved on to Matrix after the freenode incident. I wouldn't go for Discord, personally I had very bad experience culture-wise there as most reverse engineering discords are very hostile and elitarian and almost narcisstic; but let's leave that unextrapolated.

I also agree with the Telegram hosted argument, and that the server-side of Telegram isn't FOSS (while e.g. the [Android FOSS](https://github.com/Telegram-FOSS-Team/Telegram-FOSS) fork is extremely nice in regards to Privacy). So I guess I'd personally also prefer Matrix+Libera Chat as well.

**Comment by kattothepast** [comment]
I had linked a Discord here and ended up deleting my comment after quickly discovering that the one I linked was a perfect example of how not to start a fork. Based on what I'm seeing, your fork is the only one I've personally seen so far that seems to understand where to begin with a split, so I hope you keep the momentum going.

I'm not in a position to contribute and will be turning off notifications, but I wanted to throw my $0.10 in here before heading out. Good luck with the fork.

**Comment by l0go** [comment]
Even as a mostly discord main, I am completely for a matrix+irc setup as I think it aligns with this project this most. I am against telegram for the same reasons as others have stated above.

**Comment by caughtquick** [comment]
> Even as a mostly discord main, I am completely for a matrix+irc setup as I think it aligns with this project this most. I am against telegram for the same reasons as others have stated above.

Creating a room on libera.chat automatically bridges it to #roomname:libera.chat. I think that's probably the best approach if we want to support both irc and matrix

**Comment by JPcode05** [comment]
> I'd also go for either Telegram or Matrix/Element to be honest, as most chats seem to have moved on to Matrix after the freenode incident. I wouldn't go for Discord, personally I had very bad experience culture-wise there as most reverse engineering discords are very hostile and elitarian and almost narcisstic; but let's leave that unextrapolated.
> 
> I also agree with the Telegram hosted argument, and that the server-side of Telegram isn't FOSS (while e.g. the [Android FOSS](https://github.com/Telegram-FOSS-Team/Telegram-FOSS) fork is extremely nice in regards to Privacy). So I guess I'd personally also prefer Matrix+Libera Chat as well.

Do not use Telegram or Discord. Matrix and Libera.Chat will be just fine.

**Comment by AnErrupTion** [comment]
There's https://matrix.to/#/#audacityfork:semisol.dev which is bridged to my Uwucoword server. I saw there was another one but it kind of splits up the community, thought I would just share it here :v
I know Discord shouldn't be used, from now on I'll just say the Matrix room.

**Comment by vchernin** [comment]
I think creating a Matrix [Space](https://element.io/blog/spaces-the-next-frontier/) and letting users join the room(s) from IRC is the best approach. A Matrix Space lets you make a folders of rooms, which is fairly similar to a Discord server but much more customizable (you don’t need to join the Space if you just want to join one room). I’d suggest making Matrix the central place for communication, as that’s what [KDE](https://community.kde.org/Matrix) and [Mozilla](https://wiki.mozilla.org/Matrix) do, and what [GNOME](https://wiki.gnome.org/Initiatives/Matrix) and [Fedora](https://discussion.fedoraproject.org/tag/matrix) are working on.

[Surface Linux](https://github.com/linux-surface/linux-surface#support) is a simple example of how it could look. Give links to join the whole Matrix Space, or to join individual rooms, or to join from Libera.

If we only want one room a Matrix Space is mostly unnecessary, but it think it’s probably handy to have several rooms (eg. development and support). Also note Spaces are technically still in beta, but they already work well and again you can join the rooms individually just fine.

**Comment by caughtquick** [comment]
I feel like opening at least a temporary room for now will allow discussion without clogging up issues. What do you think @cookiengineer?

**Comment by cosmicmocha** [comment]
Has this been solved? Seems like an easy issue and would make it much easier to collaborate/discuss this project.

**Comment by ajayyy** [comment]
We have one [here](https://github.com/temporary-audacity/audacity/issues/7#issuecomment-873684597) and [one made for @AnErrupTion's fork](https://matrix.to/#/#audacityfork:semisol.dev). Both not official. Probably best to wait for a name to make a proper irc channel.

Edit: There is now a third channel that is "official", but temporary https://matrix.to/#/##temporary-audacity:libera.chat

**Comment by vchernin** [comment]
It's possible to rename a Matrix room or Space, and Matrix-IRC bridges should be able to adjust to that.

If we do make a temporary Space/set of rooms it should hae a very generic and "unbiased" name. As in it should not be any name that's being voted on, since that's just inviting trouble.

I'd say just name it temporary-audacity or something as that's recognizable (it's the repo name). Then perhaps make a few generic rooms like "support" and "compiling" and "general", along with some hotter topics like "name-debate" and "funding" and "branding" (these are just random suggestions, I'm sure there's a better way of doing this. [See Fedora's current room proposal](https://discussion.fedoraproject.org/t/matrix-server-channel-setup/29844/8)).

Also I see there's [now some official moderators as part of the repo](https://github.com/temporary-audacity/audacity/issues/48) that cookieengineer appointed. Ideally they should be the ones with admin privileges instead of picking other people, to keep it simple.

**Comment by caughtquick** [comment]
> It's possible to rename a Matrix room or Space, and Matrix-IRC bridges should be able to adjust to that.
> 
> If we do make a temporary Space/set of rooms it should hae a very generic and "unbiased" name. As in it should not be any name that's being voted on, since that's just inviting trouble.
> 
> I'd say just name it temporary-audacity or something as that's recognizable (it's the repo name). Then perhaps make a few generic rooms like "support" and "compiling" and "general", along with some hotter topics like "name-debate" and "funding" and "branding" (these are just random suggestions, I'm sure there's a better way of doing this. [See Fedora's current room proposal](https://discussion.fedoraproject.org/t/matrix-server-channel-setup/29844/8)).
> 
> Also I see there's [now some official moderators as part of the repo](https://github.com/temporary-audacity/audacity/issues/48) that cookieengineer appointed. Ideally they should be the ones with admin privileges instead of picking other people, to keep it simple.

I'm going to wait for @cookiengineer to make that decision just he in case he wants a specific homeserver to use or something of that natures (encryption, mods, etc)

**Comment by EndlessEden** [comment]
While im not up-to-date on the topic, i recall there being a big privacy concern with Matrix(matrix.org) recently?

**Comment by ajayyy** [comment]
@EndlessEden There has been a breach on the matrix.org homeserver before, but you can register on any homeserver.

**Comment by emabrey** [comment]
Libera states that ["Project channels are reserved for on-topic channels as per our on-topic projects, represented by owners with an official claim to that name." ](https://libera.chat/chanreg#project-channels) We currently don't have a name until #33 is complete. So, instead of creating the permanent project channel, I'm current attempting to create [a community channel](https://libera.chat/chanreg#community-channels-1) to give us a place to congregate until then (as a community channel doesn't have the name ownership requirement). If that works out then once we decide on a name hopefully we will migrate (and there is a process to acquire a name that is squatted on, so that shouldn't be a huge problem if it unfortunately does happen). I am currently working on getting this setup with representatives of Libera.

**Comment by nazunalika** [comment]
> I'd also go for either Telegram or Matrix/Element to be honest, as most chats seem to have moved on to Matrix after the freenode incident. I wouldn't go for Discord, personally I had very bad experience culture-wise there as most reverse engineering discords are very hostile and elitarian and almost narcisstic; but let's leave that unextrapolated.

I'm in favor of Matrix+IRC (Libera). Because then in the future, you can link the channel to a libera IRC channel once a name is established. Currently at Rocky Linux for example, we are using Mattermost with a bridge to IRC. And then we have some rooms in matrix bridged with IRC, so the community isn't completely fractured. We haven't had problems with this.

**Comment by caughtquick** [comment]
> > I'd also go for either Telegram or Matrix/Element to be honest, as most chats seem to have moved on to Matrix after the freenode incident. I wouldn't go for Discord, personally I had very bad experience culture-wise there as most reverse engineering discords are very hostile and elitarian and almost narcisstic; but let's leave that unextrapolated.
> 
> 
> 
> I'm in favor of Matrix+IRC (Libera). Because then in the future, you can link the channel to a libera IRC channel once a name is established. Currently at Rocky Linux for example, we are using Mattermost with a bridge to IRC. And then we have some rooms in matrix bridged with IRC, so the community isn't completely fractured. We haven't had problems with this.

It's easier to just create the room on irc where it just gets automatically bridged to matrix

**Comment by vchernin** [comment]
> I'm in favor of Matrix+IRC (Libera). Because then in the future, you can link the channel to a libera IRC channel once a name is established. Currently at Rocky Linux for example, we are using Mattermost with a bridge to IRC. And then we have some rooms in matrix bridged with IRC, so the community isn't completely fractured. We haven't had problems with this.

Furthermore, Matrix should let you bridge Mattermost and IRC, so you could potentially streamline all your rooms to be accessible on 3 platforms.

**Comment by vchernin** [comment]
> I'm in favor of Matrix+IRC (Libera). Because then in the future, you can link the channel to a libera IRC channel once a name is established. Currently at Rocky Linux for example, we are using Mattermost with a bridge to IRC. And then we have some rooms in matrix bridged with IRC, so the community isn't completely fractured. We haven't had problems with this.

Furthermore, Matrix should let you bridge Mattermost and IRC, so you could potentially streamline all your rooms to be accessible on 3 platforms.

> It's easier to just create the room on irc where it just gets automatically bridged to matrix

Indeed it's quite easy to join a libera room from Matrix. However it seems like creating the room in Matrix is perhaps best once everything's set up. For example GNOME had some issues with the way they first setup Matrix + IRC, but now they are aiming to make Matrix the central place of communication as that seems to be a better experience. Note that's a bit of a simplification, [see the lengthy writeup here](https://discourse.gnome.org/t/irc-matrix-and-thanks-for-all-the-kicks/6482).

 > At an even larger scale, the GNOME project is a successful project used by many others. There is a global movement of organisations getting out of silos. The open source community is widely adopting a federated system: Mozilla, Fedora, KDE, Debian, Archlinux… all those organisations are either Matrix-first or are transitioning to Matrix. If GNOME decided to stand out for the sake of it and decided to use another platform, it would self-segregate itself from others.

**Comment by emabrey** [comment]
So, change of plans. After speaking with a representative of Libera, we can't have a community channel on Libera **yet**.  However, I have gone ahead and setup a _different_ kind of channel which doesn't require quite the same level of proof. That channel is registered as `##temporary-audacity` (note the two octothorpes `##`, it matters). You can[ access it using your personal IRC software of choice](https://libera.chat/guides/connect#main) or using [the Libera webchat](https://web.libera.chat/).

Please note that we may need to add a requirement for an invitation or a nick registration on Libera if the moderation issue we've had on Github Issues follows us there. I'd prefer not to do that though, as I think it violates the spirit of openness, but I also don't have infinite time to moderate messages in an IRC chat by issuing ChanServ FLAG commands on an ongoing basis. Perhaps we can handle a more permanent chat moderation responsibility at a later date once we have a more permanent place (which it sounds like might potentially be a different location or a co-hosted setup depending on consensus).

I want to disclose, in the interest of transparency, that I currently have my nick `emabrey` marked as the chanop and sole channel founder, though if that temporary concession makes people uncomfortable I can empower some other contributors to be founders (as replacements or additional). Note that `+F` founder flag is the highest authority regarding channel moderation (higher than even the `+f` founder flag; there must be at least one `+F`, as far as I can tell). The `+F` flag lets me potentially delete the channel or otherwise ban or empower moderators or other founders, so I wanted to be explicitly clear about having it since it could potentially give me an unequal amount of control if were to abuse it (though I of course do not plan on doing so). I've made sure to secure the `emabrey` nick with a very secure (strong and unique) password to make sure nobody gets access to the `+F` flagged account. I would relinquish the `+F` flag if the other contributors/the community wanted someone else to do it. If the community/contributors don't seem to object then I will keep the `+F` flag for the temporary channel `##temporary-audacity` while I setup the more official project channel whose name is blocked by #33. I believe Libera expects that I will continue to be the point-of-contact by default because I am chanop of this channel, but that could be addressed. Hopefully by then we can have a more opt-in process for who is going to be `+F` and/or chanop on the permanent channel. 

I'm going to assign this issue to myself since that seems reasonable.

**Comment by caughtquick** [comment]
@emabrey I joined using matrix and don't have permission to chat, could you fix the when you get the chance.

**Comment by caughtquick** [comment]
This channel is also joinable at ##audacity-fork:libera.chat

https://matrix.to/#/##temporary-audacity:libera.chat

**Comment by Semisol** [comment]
> There's [matrix.to/#/#audacityfork:semisol.dev](https://matrix.to/#/#audacityfork:semisol.dev) which is bridged to my Uwucoword server. I saw there was another one but it kind of splits up the community, thought I would just share it here :v
> I know Discord shouldn't be used, from now on I'll just say the Matrix room.

I can cut the bridge if needed, planning on doing that

**Comment by emabrey** [comment]
Both the Matrix and IRC chatrooms are bi-directionally connected (thanks to @caughtquick, @Semisol and @ajayyy  for helping me verify that it worked correctly). You can use either IRC or Matrix and still receive all the messages from either platform, meaning you are free to use whichever you prefer.


### If you prefer Matrix:

- If you just want to use the default Matrix web client, Element, you also can setup an account and utilize the client [here](https://app.element.io/#/room/##temporary-audacity:libera.chat)
- Otherwise, [Matrix.to](https://matrix.to/#/##temporary-audacity:libera.chat) allows you to pick which Matrix client you want to use

### If you prefer IRC:

- If you just want to use the default IRC web client you can use [the Libera webchat](https://web.libera.chat/)
- Otherwise, see these [access instructions for an IRC client connection to libre.chat](https://libera.chat/guides/connect#main)

**Comment by Fuchs** [comment]
Hi, I am the representative of groups and projects on Libera Chat. 
I am not aware that we have been contacted, and I'm pretty sure you could have a community or even a project channel, and after a short discussion internally I'm not sure who told you that you can't have a channel yet. Apologies for the confusion generated there.

Feel free to contact me on Libera, my name there is "Fuchs", I'll gladly help you out to get a channel, you can of course have one. 
Or you can e-mail in to  projects@libera.chat if you prefer e-mail. 

Kind regards, 

Christian (Fuchs)

**Comment by l0go** [comment]
@emabrey Whenever I join through matrix it bans me, should I join through an IRC client instead?

**Comment by Semisol** [comment]
> @emabrey Whenever I join through matrix it bans me, should I join through an IRC client instead?

Probably, there is a +r requirement (IRC required registration) soo

**Comment by caughtquick** [comment]
> @emabrey Whenever I join through matrix it bans me, should I join through an IRC client instead?

Message @NickServ:libera.chat and register, you can see how to register by sending Nixkserv `help`

**Comment by l0go** [comment]
> > @emabrey Whenever I join through matrix it bans me, should I join through an IRC client instead?
> 
> Message @NickServ:libera.chat and register, you can see how to register by sending Nixkserv `help`

I have used IRC before, but thanks!

**Comment by Semisol** [comment]
> > > @emabrey Whenever I join through matrix it bans me, should I join through an IRC client instead?
> > 
> > 
> > Message @NickServ:libera.chat and register, you can see how to register by sending Nixkserv `help`
> 
> I have used IRC before, but thanks!

Yeah, its mostly the same but you send to `@username-not-channel-nick:libera.chat` instead of to direct usernames

**Comment by peepo5** [comment]
I will defo support a matrix group, also maybe make a Community (new feature)?
You could organize rooms when you make official communication.

**Comment by vchernin** [comment]
> I will defo support a matrix group, also maybe make a Community (new feature)?
> 
> You could organize rooms when you make official communication.

Communities are a old and poorly designed Matrix feature. They are being replaced with Spaces which is what we should use if we want a Matrix group.

**Comment by Pythone** [comment]
> I will defo support a matrix group, also maybe make a Community (new feature)?
> You could organize rooms when you make official communication.

yes
I will make it

**Comment by Pythone** [comment]
nvm, it is already made.

**Comment by Pythone** [comment]
# Removed

**Comment by emabrey** [comment]
There is already a chatroom set up. We are working on making sure it is ready for the public. 

@Pythone Thank you, but please do not create additional rooms. Please also remove your link to avoid confusion.

**Comment by Pythone** [comment]
> There is already a chatroom set up. We are working on making sure it is ready for the public.
> 
> @Pythone Thank you, but please do not create additional rooms. Please also remove your link to avoid confusion.

ok
I will

**Comment by Pythone** [comment]
also marked it unofficial

**Comment by Pythone** [comment]
I got banned from the official server on matrix while working on the logo

**Comment by emabrey** [comment]
If you attempted to join and got an `err_needreggednick` error that is expected and we will be addressing that when we open it up to the public. If you aren't registered you can't get in. To be clear, if that is what happened then you were not banned.

**Comment by TheEvilSkeleton** [comment]
IMO Matrix would be the best platform. Many projects have moved from IRC to Matrix, and IRC is really unintuitive because it does things very differently compared to other platforms.

When people want to ask a question, they don't want to start spending time on how to use NICKSERV and understand what the awful LiberaChat docs is trying to say. Matrix, specifically Element, is really simple to use, and it's the most used, mature and known client. Plus you can use your Google, GitHub, GitLab accounts to create your account. By default it uses matrix.org so it also has some "default" settings to make it more straightforward.

We can always use the Matrix IRC Bridge (matrix-appservice-irc), but this is a similar process to using IRC directly, so you still have to toy around with NICKSERV if you never have.

**Comment by n0toose** [comment]
Our chat is accessible on `#tenacity` over at [Libera](https://libera.chat).

You can access it on Matrix [here](https://matrix.to/#/#tenacity:libera.chat).
